### ISSUE TITLE
Potential Redundancy in Field Strength Ep Logging with Ptx Adjustment

### ISSUE THREAD

**Issue by drcaguiar** [eeveetza/Py1812#5]
I would like to point out a potential oversight in the P1812.bt_loss function regarding the logging of the field strength Ep after its adjustment for transmitter power (Ptx). Specifically, the assignment made on line 432 directly before logging:

`Ep = EpPtx`

This sequence results in the Ep value being logged twice with identical values, despite the second log entry being annotated to indicate adjustment with Ptx. The direct assignment Ep = EpPtx on line 432 effectively eliminates any distinction between the pre-adjusted and post-adjusted values of Ep.

**Comment by eeveetza** [comment]
Thank you for this. Indeed, the assignment `Ep = EpPtx` needs to be moved below the logging block.

**Comment by eeveetza** [comment]
I believe that the issue can be closed now.

**Comment by drcaguiar** [comment]
Fixed.
