### ISSUE TITLE
Transmitter power not scaled when running with debug=False

### ISSUE THREAD

**Issue by Daniel-Goncalves** [eeveetza/Py1812#7]
After Issue #5 the transmitter power assignment in the P1812.bt_loss function was moved to below the logging block. Though, it was moved inside the "if" statment, so when the debug variable is not set, the tx power is **completely unconsidered**.

```
if debug:
    
    # logs here
 
    Ep = EpPtx
```

I believe the correct would be remove one identation from it, so the Ep would be assigned in any case. The way it is the results are highly influencied.

**Comment by eeveetza** [comment]
Thank you, you are right. The latest patch applies the correct indentation. 
With this, the issue can be closed.
